name: Create GitHub Release from pyproject.toml version

on:
  push:
    branches:
      - main
#   pull_request:
#     types: [closed]
#     branches:
#       - main
#     if: github.event.pull_request.merged == true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Get package version
        id: package_version
        run: |
          VERSION=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)
          echo "PACKAGE_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Create New GitHub Release
        run: |
          if gh release view "${{ env.PACKAGE_VERSION }}" > /dev/null 2>&1; then
            echo "::warning::Push to main without a new package version."
            exit 1
          else
            gh release create ${{ env.PACKAGE_VERSION }} \
              --title "Release v${{ env.PACKAGE_VERSION }}" \
              --body "Automated release created from push to main branch." \
              --draft=false \
              --prerelease=false
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

